apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: pulseboard
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://pulseboard:pulseboard@postgres:5432/pulseboard"
  GITHUB_CLIENT_ID: "Ov23liIzZK5B91nZ2act"
  GITHUB_CLIENT_SECRET: "5a75f509d183492da88efa04b38bc1f39f6b8a73"
  GITHUB_REDIRECT_URI: "https://pulseboard.duckdns.org/auth/github/callback"
  JWT_SECRET_KEY: "pulseboard-k8s-secret-key"
